spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mbf_prod
    username: mbf_prod_user
    password: gram
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false